# Generated by Django 4.2.23 on 2025-09-01 12:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Marka Adı')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Web Sitesi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Şehir')),
                ('country', models.CharField(default='Türkiye', max_length=50, verbose_name='Ülke')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Posta Kodu')),
                ('tax_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Vergi Numarası')),
                ('tax_office', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vergi Dairesi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BrandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('currency_symbol', models.CharField(default='₺', max_length=5, verbose_name='Para Birimi Sembolü')),
                ('default_corridor_count', models.PositiveIntegerField(default=5, verbose_name='Varsayılan Koridor Sayısı')),
                ('default_cell_count', models.PositiveIntegerField(default=10, verbose_name='Varsayılan Hücre Sayısı')),
                ('qr_code_prefix', models.CharField(blank=True, help_text='QR kodlarının başına eklenecek önek', max_length=10, null=True, verbose_name='QR Kod Öneki')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='E-posta Bildirimleri')),
                ('low_stock_alert', models.BooleanField(default=True, verbose_name='Düşük Stok Uyarısı')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, verbose_name='Düşük Stok Eşiği')),
                ('primary_color', models.CharField(default='#007bff', help_text='Hex renk kodu (örn: #007bff)', max_length=7, verbose_name='Ana Renk')),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Hex renk kodu (örn: #6c757d)', max_length=7, verbose_name='İkincil Renk')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='brands.brand', verbose_name='Marka')),
            ],
            options={
                'verbose_name': 'Marka Ayarları',
                'verbose_name_plural': 'Marka Ayarları',
            },
        ),
    ]
