# Generated by Django 4.2.23 on 2025-09-01 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_type', models.CharField(choices=[('product', 'Ürün'), ('warehouse', 'Depo'), ('corridor', 'Koridor'), ('cell', 'Hücre'), ('shop', 'Mağaza'), ('brand', 'Marka')], max_length=20, verbose_name='QR Türü')),
                ('object_id', models.CharField(max_length=255, verbose_name='Nesne ID')),
                ('qr_data', models.TextField(help_text='QR kodunda saklanan veri', verbose_name='QR Veri')),
                ('qr_image', models.ImageField(upload_to='qr_codes/', verbose_name='QR Resmi')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='brands.brand', verbose_name='Marka')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qr_codes', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'QR Kod',
                'verbose_name_plural': 'QR Kodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Tarayıcı Bilgisi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Enlem')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Boylam')),
                ('scan_context', models.CharField(blank=True, help_text='Taramanın yapıldığı bağlam (örn: inventory, pickup, delivery)', max_length=100, null=True, verbose_name='Tarama Bağlamı')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarama Tarihi')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='qr_codes.qrcode', verbose_name='QR Kod')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to=settings.AUTH_USER_MODEL, verbose_name='Tarayan')),
            ],
            options={
                'verbose_name': 'QR Tarama',
                'verbose_name_plural': 'QR Taramalar',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='QRPrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Yazdırma İşi Başlığı')),
                ('print_format', models.CharField(choices=[('label', 'Etiket'), ('a4', 'A4 Sayfa'), ('thermal', 'Termal Yazıcı')], default='label', max_length=20, verbose_name='Yazdırma Formatı')),
                ('copies', models.PositiveIntegerField(default=1, verbose_name='Kopya Sayısı')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('printing', 'Yazdırılıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('print_settings', models.JSONField(default=dict, help_text='Yazdırma ayarları JSON formatında', verbose_name='Yazdırma Ayarları')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Hata Mesajı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Başlama Tarihi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='brands.brand', verbose_name='Marka')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('qr_codes', models.ManyToManyField(related_name='print_jobs', to='qr_codes.qrcode', verbose_name='QR Kodlar')),
            ],
            options={
                'verbose_name': 'QR Yazdırma İşi',
                'verbose_name_plural': 'QR Yazdırma İşleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
